services:
  mlir-rs-test:
    image: mlir-rs-test:latest
    build: .
    volumes:
      - ..:/mlir-rs
    command: /bin/sh -c "cd /mlir-rs && make setup && ./docker/scripts/test-all.sh"
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    environment:
      - CARGO_TARGET_DIR=/target
