name: pre-check

# on:
#  workflow_dispatch:

on:
  push:
    branches:
      - moses/665-mlir-rs-build-and-test-pipelines

env:
  CARGO_TERM_COLOR: always
jobs:
  valgrind-check:
    runs-on: ubuntu-latest
    container:
      image: icr.io/action/rust
      options: --security-opt seccomp=unconfined
      env:
        HOME: /root
      credentials:
        username: iamapikey
        password: ${{ secrets.IBM_CLOUD_REGISTRY_KEY }}
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - name: set git config
        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
      - uses: actions/checkout@v4
      - name: Install valgrind
        run: apt install -y valgrind
      - name: Setup runner
        run: make setup
      - name: Testing mlir-rs w/ valgrind
        run: make test-valgrind
      
  address-sanitizer-check:
    runs-on: ubuntu-latest
    container:
      image: icr.io/action/rust
      options: --security-opt seccomp=unconfined
      env:
        HOME: /root
      credentials:
        username: iamapikey
        password: ${{ secrets.IBM_CLOUD_REGISTRY_KEY }}
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - name: set git config
        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
      - uses: actions/checkout@v4
      - name: Setup runner
        run: make setup
      - name: Testing mlir-rs w/ rust address sanitizer 
        run: make test-address
      
  memory-sanitizer-check:
    runs-on: ubuntu-latest
    container:
      image: icr.io/action/rust
      options: --security-opt seccomp=unconfined
      env:
        HOME: /root
      credentials:
        username: iamapikey
        password: ${{ secrets.IBM_CLOUD_REGISTRY_KEY }}
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - name: set git config
        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
      - uses: actions/checkout@v4
      - name: Setup runner
        run: make setup
      - name: Testing mlir-rs w/ rust memory sanitizer
        run: make test-memory