name: pre-check

# on:
#   pull_request:
#     branches:
#       - "main"
#   merge_group:
#     branches:
#       - "main"
on:
  push:
    branches:
      - moses/665-mlir-rs-build-and-test-pipelines

env:
  CARGO_TERM_COLOR: always
jobs:
  dup-check:
    runs-on: dup-check
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
  code-coverage-mlir-rs:
    runs-on: ubuntu-latest
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - name: set git config
        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
      - uses: actions/checkout@v4
      - name: Setup runner
        run: sudo ./utils/setup.sh
      - name: Setup mlir-rs
        run: make setup
      - name: code-coverage-mlir-rs
        run: make code-coverage
      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./cobertura.xml
          threshold: 80
          fail: false
          publish: true
          coverage-summary-title: "mlir-rs: Code Coverage Summary"
      - name: print-result
        shell: bash
        run: echo "Code Coverage Passed"
  test-mlir-rs:
    runs-on: ubuntu-latest
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - name: set git config
        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
      - uses: actions/checkout@v4
      - name: Setup runner
        run: sudo ./utils/setup.sh
      - name: Setup mlir-rs
        run: make setup
      - name: run-checks-mlir-rs
        run: make github-checks
      - name: Testing mlir-rs no sanitizer
        run: make test
      - name: Testing mlir-rs address sanitizer 
        if: success() || failure()
        run: make test-address
      - name: Testing mlir-rs memory sanitizer
        if: success() || failure()
        run: make test-memory
      - name: Testing mlir-rs with valgrind
        if: success() || failure()
        run: make test-valgrind