name: pre-check

on:
  pull_request:
    branches:
      - "main"
  merge_group:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always
jobs:
  code-coverage-mlir-rs:
    runs-on: ubuntu-latest
    container:
      image: icr.io/action/rust
      options: --security-opt seccomp=unconfined
      env:
        HOME: /root
      credentials:
        username: iamapikey
        password: ${{ secrets.IBM_CLOUD_REGISTRY_KEY }}
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - name: set git config
        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
      - uses: actions/checkout@v4
      - name: Setup mlir-rs
        run: make setup
      - name: code-coverage-mlir-rs
        run: make code-coverage
      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./cobertura.xml
          threshold: 80
          fail: false
          publish: true
          coverage-summary-title: "mlir-rs: Code Coverage Summary"
      - name: print-result
        shell: bash
        run: echo "Code Coverage Passed"

  lint-mlir-rs:
    runs-on: ubuntu-latest
    container:
      image: icr.io/action/rust
      options: --security-opt seccomp=unconfined
      env:
        HOME: /root
      credentials:
        username: iamapikey
        password: ${{ secrets.IBM_CLOUD_REGISTRY_KEY }}
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - name: set git config
        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
      - uses: actions/checkout@v4
      - name: Setup mlir-rs
        run: make setup
      - name: Lint and format check
        run: make github-checks

  test-mlir-rs:
    runs-on: ubuntu-latest
    container:
      image: icr.io/action/rust
      options: --security-opt seccomp=unconfined
      env:
        HOME: /root
      credentials:
        username: iamapikey
        password: ${{ secrets.IBM_CLOUD_REGISTRY_KEY }}
    steps:
      - name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
      - name: set git config
        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
      - uses: actions/checkout@v4
      - name: Setup mlir-rs
        run: make setup
      - name: mlir-rs test
        run: make test